### ISSUE TITLE
Flutter v1.22.0 Error 

### ISSUE THREAD

**Issue by mayankjanmejay** [JonasWanke/swipeable_page_route#4] opened 2020-10-06 10:38 UTC
Hi I updated to the new flutter version and your plugin has some dependencies issues I am getting the following error. 

And because every version of swipeable_page_route depends on list_diff ^1.3.0 which depends on async >=2.2.0 <2.5.0, flutter_test from sdk is incompatible with swipeable_page_route.
So, because zaa depends on both swipeable_page_route ^0.1.4 and flutter_test any from sdk, version solving failed.

![Capture](https://user-images.githubusercontent.com/35850067/95191623-aa379880-07d9-11eb-8146-75bf54fbed50.PNG)

**Environment:**

- Device:  Emulator
- OS version:  Android 10
- Package version:  flutter 1.22.0

**Comment by JonasWanke** [comment] 2020-10-06 18:54
As the error message describes, the `list_diff` dependency restricts compatible versions of `async` to `>=2.2.0 <2.5.0`. There's already an issue (including a workaround) for that: marcelgarus/list_diff#4.

Closing this as a duplicate of #3

**Closed by JonasWanke** 2020-10-06 18:54 UTC
Labels: T: fix
