### ISSUE TITLE
Bug with the color model for flutter 3.27

### ISSUE THREAD

**Issue by nimr77** [JonasWanke/swipeable_page_route#80] opened 2024-12-16 13:23 UTC
- mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class LabColor extends cm.LabColor
      ^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/painting.dart:186:20: Context: 'Color.colorSpace' is defined here.
  final ColorSpace colorSpace;
                   ^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/painting.dart:180:16: Context: 'Color.g' is defined here.
  final double g;
               ^
org-dartlang-sdk:///flutter/lib/ui/painting.dart:177:16: Context: 'Color.r' is defined here.
  final double r;
               ^
../../../../.pub-cache/hosted/pub.dev/flutter_color_models-1.3.3+2/lib/src/models/oklab_color.dart:9:7: Error: The non-abstract class 'OklabColor' is missing implementations for these members:
 - Color.colorSpace
 - Color.g
 - Color.r
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class OklabColor extends cm.OklabColor
      ^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/painting.dart:186:20: Context: 'Color.colorSpace' is defined here.
  final ColorSpace colorSpace;

**Comment by nimr77** [comment] 2024-12-16 14:08
I made a fix here 
https://github.com/JonasWanke/swipeable_page_route/pull/81

**Comment by JonasWanke** [comment] 2024-12-17 16:17
Duplicate of #79

**Closed by JonasWanke** 2024-12-17 16:17 UTC
Labels: T: Fix
