### ISSUE TITLE
Tab Bar is not working with swipeable_page_route

### ISSUE THREAD

**Issue by Alfaizkhan** [JonasWanke/swipeable_page_route#12] opened 2021-04-28 06:24 UTC

**Comment by JonasWanke** [comment] 2021-04-28 08:37
This looks like a duplicate of #6 if you want to achieve horizontal scrolling inside the page:

> Unfortunately, I haven't found a way to allow horizontal scrolls between tabs in the content area, but to swipe back when the user is on the left-most tab. Hence, there's an extra parameter in the `SwipeablePageRoute` constructor: setting `onlySwipeFromEdge` to `true` allows the user to swipe back (if they start the swipe near the left edge of the screen) or swipe between tabs (by starting their swipes further to the right). […] – https://github.com/JonasWanke/swipeable_page_route/issues/6#issuecomment-744340540

If that doesn't solve your issue, could you please post a small code sample demonstrating the problem?

**Closed** 2021-10-30 16:14 UTC
Labels: T: fix
